### ISSUE TITLE
Failing

### ISSUE THREAD

**Issue by klalle** [martindb/mpcnc_posts_processor#1]
Nice code you've got there! 
I can't get F360 to process anything with this one though... It'll only give me a file named "name.gcode.failed" Any ideas?
/Kalle

**Comment by martindb** [comment]
Thanks Kalle.
Are you using all default options of the posts processor? Can you share me your fusion 360 file?

**Comment by klalle** [comment]
Yes, all default options! 
I just downloaded the file and put it in the post processor folder, then opened a model and tried a couple of 2D-toolpaths (that works with the V9 version from Vicious)... 
So I guess it's pointless to upload the file to you, it's identical to the one here!

**Comment by klalle** [comment]
Aha, you want the CAD/CAM file:  [Link](https://github.com/klalle/Marlin_RC7_LCD_Customization/blob/master/Example%20of%20use/)

**Comment by martindb** [comment]
mmm I just imported your remote cad/cam file, regenerate the toolpaths and export with my posts processor script just right.... attached is the gcode.
[remote_v1.gcode.zip](https://github.com/martindb/mpcnc_posts_processor/files/706649/remote_v1.gcode.zip)

Are you using Mac or Windows? may be some difference with this? (I've developed in Mac).
Try to open the csp file with a text editor like notepad++ and save in windows format.

**Comment by klalle** [comment]
Didn't make a difference!
In the log-file this is the error message:

Information: Configuration: MPCNC Milling and Laser/Plasma cutter
Information: Vendor: Autodesk
Information: Posting intermediate data to 'C:\Users\Kalle\Dropbox\CNC - Fräs\GCode to fräs\test.gcode'
Information: Total number of warnings: 1
Error: Failed to post process. See below for details.
...
Code page changed to '1252  (ANSI - Latin I)'
Start time: Sunday, January 15, 2017 2:45:28 PM
Code page changed to '20127 (US-ASCII)'
Post processor engine: 4.2.1 41279
Configuration path: C:\Users\Kalle\AppData\Local\Autodesk\webdeploy\production\1c8eda3d042f236f121d6fb4e850f0621b6f700b\Applications\CAM360\Data\Posts\MPCNC_Mill_Laser.cps
Include paths: C:\Users\Kalle\AppData\Local\Autodesk\webdeploy\production\1c8eda3d042f236f121d6fb4e850f0621b6f700b\Applications\CAM360\Data\Posts
Configuration modification date: Sunday, January 15, 2017 2:43:16 PM
Output path: C:\Users\Kalle\Dropbox\CNC - Fräs\GCode to fräs\test.gcode
Checksum of intermediate NC data: 5a04afee06f6a396299d181f47f4db6f
Checksum of configuration: cd26efec05be79c10e104f833249f186
Vendor url: http://cam.autodesk.com
Legal: Copyright (C) 2012-2016 by Autodesk, Inc.
**Warning: The post configuration has been not been certified for use with this version of the post processor. The post configuration has to be re-certified.**
**The post configuration has been certified for level 1 but requires level 2.**
Generated by: Fusion 360 CAM 2.0.2604
...
Error(C:\Users\Kalle\AppData\Local\Autodesk\webdeploy\production\1c8eda3d042f236f121d6fb4e850f0621b6f700b\Applications\CAM360\Data\Posts\MPCNC_Mill_Laser.cps:120): **ReferenceError: toolChangeEnabled is not defined**
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Stack dump:
onSection()@C:\Users\Kalle\AppData\Local\Autodesk\webdeploy\production\1c8eda3d042f236f121d6fb4e850f0621b6f700b\Applications\CAM360\Data\Posts\MPCNC_Mill_Laser.cps:119

Failed while processing onSection() for record 273.
Error: Failed to invoke function 'onSection'.
Error: Failed to invoke 'onSection' in the post configuration.
Error: Failed to execute configuration.
Stop time: Sunday, January 15, 2017 2:45:29 PM
Post processing failed.

**Comment by martindb** [comment]
It's strange.... toolChangeEnabled it's defined in the user properties (line 31).

**Comment by klalle** [comment]
Accept the pull request I just made... your mac doesn't need the "**properties.**" in front of your custom properties, but obviously mine does, and you had missed them on some places! 
Now it works!
